# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chemdb', '0002_structure_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='rId',
        ),
    ]
