# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemdb', '0003_remove_structure_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='mol_formula',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='structure',
            name='mol_weight',
            field=models.FloatField(default=0),
        ),
    ]
