# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemdb', '0004_auto_20160314_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='mol_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
