# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chemdb', '0005_structure_mol_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='mol_stock',
            field=models.FloatField(default=0),
        ),
    ]
